name: Build and test

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install -y libelf-dev
    - name: Prepare environment
      run: |
        rustup toolchain install nightly
        rustup override set nightly
        rustup component add rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
